{{- if .Values.ipAddressKeycloakIngressgateway }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: keycloak-ingressgateway
  namespace: metallb-system
spec:
  addresses:
    - {{ .Values.ipAddressKeycloakIngressgateway }}/32
  serviceAllocation:
    priority: 50
    namespaces:
      - istio-system
    serviceSelectors:
      - matchLabels:
          app: keycloak-ingressgateway
{{- end }}
