{{- if .Values.ipAddressAdminIngressgateway }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: admin-ingressgateway
  namespace: metallb-system
spec:
  ipAddressPools:
    - admin-ingressgateway
{{- end }}
