resources:
- https://raw.githubusercontent.com/metallb/metallb/v0.13.11/config/manifests/metallb-native.yaml

images:
- name: quay.io/metallb/controller
  newName: registry1.dso.mil/ironbank/opensource/metallb/controller
  # renovate: datasource=github-tags depName=metallb/metallb versioning=semver
  newTag: v0.13.11
- name: quay.io/metallb/speaker
  newName: registry1.dso.mil/ironbank/opensource/metallb/speaker
  # renovate: datasource=github-tags depName=metallb/metallb versioning=semver
  newTag: v0.13.11

patches:
  - target:
      kind: Deployment
      name: controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: controller
      spec:
        template:
          spec:
            securityContext:
              fsGroup: 65532
              runAsNonRoot: true
              runAsUser: 65532
              runAsGroup: 65532
  - target:
      kind: DaemonSet
      name: speaker
    patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: speaker
      spec:
        template:
          spec:
            securityContext:
              fsGroup: 65532
              runAsUser: 0
